### ISSUE TITLE
KaOS fails to install GRUB

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/core#10]
Something goes wrong, if i install KaOS on BIOS, it works fine via UEFI:

GRUB doesnt appear on the first reboot, instead does a black screen, which say that there is no OS installed. 

https://gist.github.com/anonymous/a186f372ed7b175f89bea0d7fec0a5ce

**Comment by demmm** [comment]
Not a core package issue but installer/Calamares issue
Irrelevant log posted, shows EFI install, closing.

**Comment by ShalokShalom** [comment]
I post the log just for my specs. :)
