### ISSUE TITLE
Plasma (Wayland)

### ISSUE THREAD

**Issue by Nithin-Reddy** [KaOSx/core#11]
I can't open Plasma (Wayland), where Plasma works well without any problems.
I get splash screen but after that I can see only my Mouse Pointer, there is blank screen, which is in blank color.
As soon as I installed Kaos, after I logged in and used plasma, I switched to Plasma (Wayland), but it crashed too many times where, I would see Kde Wallet for encrypting keys, which ever option I click on it would crash and take me to Login screen, even touchpad click isn't working in wayland (I checked it out in that two minutes to select a option for Kde Wallet), Iam using latest Kaos version i.e.,2016.04

I hade a log file in my /var/log/Xorg.0.log
I don't known whether it is related to this topic or not so i'm not posting it here.

**Comment by demmm** [comment]
Wayland is not ready for daily use (and certainly is not a core issue, kwayland/kwin are apps), it is still in experimental stage, and won't work at all with certain graphics drivers.  Only drivers known to work consistently reasonably well are ATI/Radeon.
Not a a KaOS issue, but upstream, not marked anywhere as ready.
Closing.
