### ISSUE TITLE
HP Laptop Wifi Connectivity Problem

### ISSUE THREAD

**Issue by kishoreuk2008** [KaOSx/core#12]
Hi I'm using an HP 15 AC650TU laptop with KaOS 2016 version. I have some problem connecting to the laptop using WiFi. To connect to the wifi I have to keep the wifi device close to the laptop or else it wont detect the wifi connection and even if i keep it close, it shows only one bar signal. Please help me. I can't use my laptop in public wifi places.

**Comment by demmm** [comment]
What driver is in use for this?  
inxi -n
Checked your logs?  Anything in journalct? dmesg?
What ISO used?  Exact name and date.  System updated?

**Comment by demmm** [comment]
No further response from submitter, closing.
