### ISSUE TITLE
Mistype on nfs-utils post-upgrade message

### ISSUE THREAD

**Issue by fjmorazan** [KaOSx/core#16]
A tiny mistype (openvpn instead of nfs-utils) from the Kdialog message comming from the build package
![screenshot_20170114_204530](https://cloud.githubusercontent.com/assets/7052764/21959968/a9eddf32-da9d-11e6-850b-3d712ff1c7cf.png)

**Comment by demmm** [comment]
Already spotted, corrected version should have been up already......

**Comment by demmm** [comment]
Correct version is up, closing, see commit:
https://github.com/KaOSx/core/commit/208f2c06b5ffe88734a8d59b310743fb0d41100d#diff-0afa8cbbe680dcdb01aa3ec1cafbc640R1
