### ISSUE TITLE
Certificate verification error on KCP-Center related to 'ca-certificates 20180409' pkg

### ISSUE THREAD

**Issue by fjmorazan** [KaOSx/core#21]
With the last update on this package whenever is used the KCP-Center python script, it throws an error about being unable to [verify](https://gist.github.com/fjmorazan/be628eee5278329b31c172a0236f4499) the certificate from github. Downgrading the pkg `ca-certificates` to `20170717` makes the helper work without issues.

**Comment by demmm** [comment]
You notice this issue only on using that script?  If so, the script probably will need adjusting.  Will wait a bit longer with moving ca-certificates to core.

**Comment by fjmorazan** [comment]
Yes, only with that script

**Comment by demmm** [comment]
If the above solution works, then I doubt it is an issue that should keep ca-certificates from moving to the core repo.  Please note if it still works, than this bug report can be closed & ca-certificate can move.

**Comment by fjmorazan** [comment]
Yes, it works without issue adding those lines

**Comment by demmm** [comment]
Issue seems ca-certificates & python related, as noted in IRC, also fails in youtube-dl:
https://gist.github.com/fjmorazan/2fb9722f04ce319d22ee9d5e859d49a2

**Comment by demmm** [comment]
ca-certificate is back to the last fully working version (2017), closing this now.  Please re-open if you still have this bug.
