### ISSUE TITLE
WiFi broken on two different systems

### ISSUE THREAD

**Issue by ShalokShalom** [KaOSx/core#22]
I always used ethernet in the last couple of months on my main machine. 

Today a friend come by and reported broken WiFi on her KaOS, which I installed recently, so I plugged in my ethernet cable into her device and saw by then that my own WiFi is also not working. 

I added a second WiFi chip via USB and that one did not work also. 

WiFi not working means here that inxi and lsusb/lspci report healthy chips and the network manager won't allow/react when I try to enable WiFi. The button is simply not working and the hardware buttons neither.

Here is the system info from both laptops:

https://ptpb.pw/k7HR
https://ptpb.pw/71JQ

**Comment by demmm** [comment]
So this is in regard the iwlwifi driver?  Make sure to get some more logs about this driver (dmesg + journalctl).
Do you have some older versions of linux-firmware in your cache?  When did the issue start?  Try to find the exact date, so it can be possible to pinpoint it to a kernel or linux-firmware update.

**Comment by demmm** [comment]
Actually, from the first system, make sure to reboot after such a major update, seems this was reported after moving to new gcc, kernel, llvm/clang, linux-firmware and a lot more, without a reboot. 
Issue still present after the needed reboot?

**Comment by ShalokShalom** [comment]
All rebooted, yeah. Issue was already there before the update.

**Comment by demmm** [comment]
Again, is the issue in which driver?  Both lists iwlwifi, thus my question, if issue is in different drivers, then open separate issue.

**Comment by ShalokShalom** [comment]
The issue is the same on all two laptops and all three wifi chips, from which two are iwlwifi and one realtek.
So yes, same issue across different drivers.

**Comment by ShalokShalom** [comment]
dmesg first device: https://www.pastefs.com/pid/87660
journalctl first device: https://www.pastefs.com/pid/87661

**Comment by demmm** [comment]
And my other questions?
>Do you have some older versions of linux-firmware in your cache? When did the issue start? Try to find the exact date, so it can be possible to pinpoint it to a kernel or linux-firmware update.

**Comment by ShalokShalom** [comment]
Since the first device was able to provide WLAN and since it was installed just recently, I dunno if its the firmware. I look up soon into the Pacman log.

**Comment by ShalokShalom** [comment]
Issue comes and goes. It once disappeared, just the be there again now. Sounds like broken hardware, while actually effects 4 different chips. What can it be?

**Comment by demmm** [comment]
Please not why this closed.  Resolved?  If so, how?

**Comment by ShalokShalom** [comment]
My private device recovered after an update. The other one not and I have no access anymore to that second device. So I could not help there anyway and If, would I boot a current live media and see what is going on. Thanks a lot for your interest. :hugs:
