### ISSUE TITLE
Systemd Manual Pages disordered

### ISSUE THREAD

**Issue by ErSoul** [KaOSx/core#26]
When querying any systemd manual page (journalctl, systemctl, systemd, etc) from the konsole (or any terminal), the text is showing with weird tabulations.

systemd man page:

![image](https://user-images.githubusercontent.com/4327047/74552503-be1d4a00-4f2b-11ea-83ae-fbdd79bfeb42.png)

Journalctl man page:

![Screenshot_20200214_131344](https://user-images.githubusercontent.com/4327047/74552835-7945e300-4f2c-11ea-9e50-df5a236caae6.png)

I have **_systemd 1:244-3_** package installed. 
Kernel: **_Linux pc 5.4.7-1 #1 SMP PREEMPT Wed Jan 1 12:02:35 UTC 2020 x86_64 GNU/Linux_**

PD: also the systemd-unit manual is missed.

**Comment by demmm** [comment]
What commands used to get that output? Regular `man systemd` has no issues here.

**Comment by ErSoul** [comment]
Yes, regular `man systemd`

Here's a screenshot from yakuake

![image](https://user-images.githubusercontent.com/4327047/74557830-697fcc00-4f37-11ea-9206-043d583cbe85.png)

And also my pacman log,  but I believe the packages installed from other sources doesn't have anything to do

[octopi-sysinfo-656544342.log](https://github.com/KaOSx/core/files/4206156/octopi-sysinfo-656544342.log)

**Comment by demmm** [comment]
This is one of the man page source files that is effected:
https://github.com/systemd/systemd/blob/master/man/journalctl.xml
Since you state it starts well down in the man page, there must be a tag misplaced in that file.
Will leave the issue open as reference point, but not something packaging/KaOS releated.

**Comment by demmm** [comment]
Seems no longer an issue, can't replicate, please re-open if you can replicate.
