### ISSUE TITLE
KaOS (2021) won't boot to graphical target (or so it seems)

### ISSUE THREAD

**Issue by AwesomeKenP** [KaOSx/core#27]
After startup, I have to switch to tty2, login, and start sddm service again:
`systemctl restart sddm`

No change made to the system configuration after install.

Running `journalctl -xb` shows:

`Jul 26 20:06:09 photon sddm[437]: Failed to read display number from pipe`
`Jul 26 20:06:09 photon sddm[437]: Could not start Display server on vt 1`

**Comment by demmm** [comment]
Not a core issue, but install info needed, see:
https://kaosx.us/docs/
https://kaosx.us/docs/#info-to-provide-for-installation-issues
Provide at least the installation.log and hardware info.
