### ISSUE TITLE
Stale dependency in libcap package file

### ISSUE THREAD

**Issue by AndrewGMorgan** [KaOSx/core#28]
https://github.com/KaOSx/core/blob/master/libcap/PKGBUILD lists ''attr" as a dependency for libcap. That dependency was dropped a while back... Specifically [libcap-2.25](https://sites.google.com/site/fullycapable/release-notes-for-libcap/older-pre-2-43-release-notes-for-libcap/releasenotesfor225).

**Comment by demmm** [comment]
Thanks for reporting.
