### ISSUE TITLE
Boost. Python error this process "userkf5/main.py srcipting running".

### ISSUE THREAD

**Issue by KardiWeb** [KaOSx/core#4]
KaOS 2015.04 ISO
Boost. Python error this process "userkf5/main.py srcipting running".
<class 'FileNotFoundError'>
[Errno 2] No such file or directory: '/etc/skel/yakukaerc'
Traceback:
  File "/usr/lib/calamares/modules/userkf5/main.py", line 83, in run
    (install_path,  user,  d,  f))

  File "/usr/lib/python3.4/shutil.py", line 245, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)

  File "/usr/lib/python3.4/shutil.py", line 108, in copyfile
    with open(src, 'rb') as fsrc:

**Comment by demmm** [comment]
This is impossible to have anything to do with a core package.
State what you are doing when you see this (I  presume it is using Calamares).
If it is calamares open an issue in that repo, with ISO versions, calamares version and so on.

**Comment by KardiWeb** [comment]
Calamares installer installation

**Comment by demmm** [comment]
Then closing this issue.
