### ISSUE TITLE
cannot enable service

### ISSUE THREAD

**Issue by lapont** [KaOSx/core#9]
'sudo systemctl start autofs.service' works OK 
'sudo systemctl enable autofs.service' does not work:
Error: Failed to execute /usr/lib/systemd/systemd-sysv-install: No such file or directory
It looks like the script systemd-sysv-install is missing

**Comment by demmm** [comment]
pacman -Qi autofs

**Comment by lapont** [comment]
autofs is already installed. The problem is that program 'systemd-sysv-install' is missing.
It is not a aytofs problem!

**Comment by demmm** [comment]
Please answer the question, I need to see the output of pacman -Qi autofs

**Comment by lapont** [comment]
[lars@kaos ~]$ pacman -Qi autofs
Name           : autofs
Version        : 5.1.1-1
Description    : A kernel-based automounter for Linux.
Architecture   : x86_64
URL            : http://freshmeat.net/projects/autofs
Licenses       : GPL2
Groups         : None
Provides       : None
Depends On     : libldap  libxml2  krb5  kmod
Optional Deps  : None
Required By    : None
Optional For   : None
Conflicts With : None
Replaces       : None
Installed Size :   2.89 MiB
Packager       : Anke Boersma <demm@kaosx.us>
Build Date     : Tue Apr 21 20:48:43 2015
Install Date   : Sat Jan 16 09:16:47 2016
Install Reason : Explicitly installed
Install Script : No
Validated By   : SHA256 Sum

**Comment by demmm** [comment]
No idea how you get the need for "systemd-sysv-install', not in the KaOS repos, nor can your error be reproduced:
```
sudo systemctl status autofs
● autofs.service - Automounts filesystems on demand
   Loaded: loaded (/usr/lib/systemd/system/autofs.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2016-01-17 14:30:43 EST; 6s ago
  Process: 16368 ExecStart=/usr/sbin/automount $OPTIONS --pid-file /run/autofs.pid (code=exited, status=0/SUCCESS)
 Main PID: 16372 (automount)
    Tasks: 5 (limit: 512)
   CGroup: /system.slice/autofs.service
           └─16372 /usr/sbin/automount --pid-file /run/autofs.pid

Jan 17 14:30:43 sdb systemd[1]: Starting Automounts filesystems on demand...
Jan 17 14:30:43 sdb systemd[1]: Started Automounts filesystems on demand.
[anke@sdb main]$ kcp -s hex
```

**Comment by lapont** [comment]
The problem is not, that autofs don't work.
The problem is, that autofs.service can't be started at boot because 'systemctl enable autofs.service' don't work.
I can start the service manually with then command 'sudo systemctl start autofs.service' and then run your command and I get the same output:
[lars@kaos ~]$ sudo systemctl status autofs
● autofs.service - Automounts filesystems on demand
   Loaded: loaded (/usr/lib/systemd/system/autofs.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2016-01-17 20:40:46 CET; 6s ago
  Process: 1574 ExecStart=/usr/sbin/automount $OPTIONS --pid-file /run/autofs.pid (code=exited, status=0/SUCCESS)
 Main PID: 1576 (automount)
    Tasks: 6 (limit: 512)
   CGroup: /system.slice/autofs.service
           └─1576 /usr/sbin/automount --pid-file /run/autofs.pid

Jan 17 20:40:46 kaos systemd[1]: Starting Automounts filesystems on demand...
Jan 17 20:40:46 kaos systemd[1]: Started Automounts filesystems on demand.
[lars@kaos ~]$

**Comment by demmm** [comment]
Yes, and the last part shows enable is working, not seen that?
Best show the output of  ```pacman-Qm```, and paste your /etc/pacman.conf

**Comment by lapont** [comment]
I try to enable the service at boot by this procedure:
found at: https://www.digitalocean.com/community/tutorials/how-to-configure-a-linux-service-to-start-automatically-after-a-crash-or-reboot-part-1-practical-examples
-----------------------------------
Make sure the service has a functional systemd init script located at /etc/systemd/system/multi-user.target.wants/service.service
Use the systemctl command to enable the service:
  sudo systemctl enable service.service
This should create a symlink in /etc/systemd/system/multi-user.target.wants/ that looks like the following (do NOT create this manually): 
 lrwxrwxrwx 1 root root 38 Aug  1 04:43 /etc/systemd/system/multi-user.target.wants/service.service -> /usr/lib/systemd/system/service.service
---------------------------------------
  sudo systemctl enable service.service relies on a program or script 'systemd-sysv-install' that does not exist

pacman -Qm gives no output
pacman -Q gives a very very very long list. Do you still find it necessary to see the whole list or can I filter the interesting lines with grep? 
My /etc/pacman.conf look læike this
#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#XferCommand = /usr/bin/curl -C - %u > %o
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options (all disabled by default)
#UseSyslog
#ShowSize
Color
#TotalDownload
CheckSpace
VerbosePkgLists
ILoveCandy

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel = Never
LocalFileSigLevel = Never
#RemoteFileSigLevel = Required

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#   - URLs will have $arch replaced by the name of the architecture
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

[core]
Include = /etc/pacman.d/mirrorlist

[main]
Include = /etc/pacman.d/mirrorlist

[apps]
Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#Server = file:///home/custompkgs

**Comment by demmm** [comment]
I'll repeat my previous paste about how to correctly enable this service.  This is not a help channel though, use the forum or IRC for that.  So far there does not seem to be any bug you reported.
```
sudo systemctl enable autofs
Password: 
Created symlink from /etc/systemd/system/multi-user.target.wants/autofs.service to /usr/lib/systemd/system/autofs.service.
```

Closing as invalid.
